# Generated by Django 3.1.1 on 2020-10-07 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to=''),
        ),
    ]
