# Generated by Django 3.1.1 on 2020-10-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todofront', '0002_auto_20201007_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='default-avatar.png', null=True, upload_to='media/'),
        ),
    ]
