# Generated by Django 3.1.1 on 2020-10-03 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20201003_2241'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
